/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as appAppRouteRouteImport } from './routes/(app)/app/route'
import { Route as appAppIndexRouteImport } from './routes/(app)/app/index'
import { Route as appAppDashboardRouteImport } from './routes/(app)/app/dashboard'
import { Route as appAppTemplatesIndexRouteImport } from './routes/(app)/app/templates/index'
import { Route as appAppDevicesIndexRouteImport } from './routes/(app)/app/devices/index'
import { Route as appAppTemplatesTemplateIdRouteImport } from './routes/(app)/app/templates/$templateId'
import { Route as appAppDevicesDeviceIdRouteImport } from './routes/(app)/app/devices/$deviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRouteRoute = appAppRouteRouteImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppIndexRoute = appAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppDashboardRoute = appAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppTemplatesIndexRoute = appAppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppDevicesIndexRoute = appAppDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppTemplatesTemplateIdRoute =
  appAppTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => appAppRouteRoute,
  } as any)
const appAppDevicesDeviceIdRoute = appAppDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => appAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof appAppRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/app/dashboard': typeof appAppDashboardRoute
  '/app/': typeof appAppIndexRoute
  '/app/devices/$deviceId': typeof appAppDevicesDeviceIdRoute
  '/app/templates/$templateId': typeof appAppTemplatesTemplateIdRoute
  '/app/devices/': typeof appAppDevicesIndexRoute
  '/app/templates/': typeof appAppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/app/dashboard': typeof appAppDashboardRoute
  '/app': typeof appAppIndexRoute
  '/app/devices/$deviceId': typeof appAppDevicesDeviceIdRoute
  '/app/templates/$templateId': typeof appAppTemplatesTemplateIdRoute
  '/app/devices': typeof appAppDevicesIndexRoute
  '/app/templates': typeof appAppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/app': typeof appAppRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/app/dashboard': typeof appAppDashboardRoute
  '/(app)/app/': typeof appAppIndexRoute
  '/(app)/app/devices/$deviceId': typeof appAppDevicesDeviceIdRoute
  '/(app)/app/templates/$templateId': typeof appAppTemplatesTemplateIdRoute
  '/(app)/app/devices/': typeof appAppDevicesIndexRoute
  '/(app)/app/templates/': typeof appAppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app/'
    | '/app/devices/$deviceId'
    | '/app/templates/$templateId'
    | '/app/devices/'
    | '/app/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/app/dashboard'
    | '/app'
    | '/app/devices/$deviceId'
    | '/app/templates/$templateId'
    | '/app/devices'
    | '/app/templates'
  id:
    | '__root__'
    | '/'
    | '/(app)/app'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(app)/app/dashboard'
    | '/(app)/app/'
    | '/(app)/app/devices/$deviceId'
    | '/(app)/app/templates/$templateId'
    | '/(app)/app/devices/'
    | '/(app)/app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAppRouteRoute: typeof appAppRouteRouteWithChildren
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app': {
      id: '/(app)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof appAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app/': {
      id: '/(app)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof appAppIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/app/dashboard': {
      id: '/(app)/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof appAppDashboardRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/app/templates/': {
      id: '/(app)/app/templates/'
      path: '/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof appAppTemplatesIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/app/devices/': {
      id: '/(app)/app/devices/'
      path: '/devices'
      fullPath: '/app/devices/'
      preLoaderRoute: typeof appAppDevicesIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/app/templates/$templateId': {
      id: '/(app)/app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof appAppTemplatesTemplateIdRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/app/devices/$deviceId': {
      id: '/(app)/app/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/app/devices/$deviceId'
      preLoaderRoute: typeof appAppDevicesDeviceIdRouteImport
      parentRoute: typeof appAppRouteRoute
    }
  }
}

interface appAppRouteRouteChildren {
  appAppDashboardRoute: typeof appAppDashboardRoute
  appAppIndexRoute: typeof appAppIndexRoute
  appAppDevicesDeviceIdRoute: typeof appAppDevicesDeviceIdRoute
  appAppTemplatesTemplateIdRoute: typeof appAppTemplatesTemplateIdRoute
  appAppDevicesIndexRoute: typeof appAppDevicesIndexRoute
  appAppTemplatesIndexRoute: typeof appAppTemplatesIndexRoute
}

const appAppRouteRouteChildren: appAppRouteRouteChildren = {
  appAppDashboardRoute: appAppDashboardRoute,
  appAppIndexRoute: appAppIndexRoute,
  appAppDevicesDeviceIdRoute: appAppDevicesDeviceIdRoute,
  appAppTemplatesTemplateIdRoute: appAppTemplatesTemplateIdRoute,
  appAppDevicesIndexRoute: appAppDevicesIndexRoute,
  appAppTemplatesIndexRoute: appAppTemplatesIndexRoute,
}

const appAppRouteRouteWithChildren = appAppRouteRoute._addFileChildren(
  appAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAppRouteRoute: appAppRouteRouteWithChildren,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
